spring.application.name=ev-charger-scheduler

spring.datasource.url=jdbc:postgresql://localhost:5432/ev_scheduler
spring.datasource.username=ev_user
spring.datasource.password=ev_pass

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

notification.service.base-url=http://localhost:8080